name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-stickers:
    name: "Build Stickers (upload to cloudinary)"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo "CLOUDINARY_NAME=${{ secrets.CLOUDINARY_NAME }}\nCLOUDINARY_KEY=${{ secrets.CLOUDINARY_KEY }}\nCLOUDINARY_SECRET=${{ secrets.CLOUDINARY_SECRET }}" > ".env"
      - run: yarn install
      - run: yarn build-stickers
